#!/usr/bin/env python3
"""Validate the deployable CCSD Board Personnel Watch bundle.

The public dashboard is generated by a separate scheduled updater.  This gate
keeps an out-of-date producer from silently replacing region-aware application
assets or republishing a low-quality full-history parse.
"""

from __future__ import annotations

import argparse
from collections import Counter
import json
from pathlib import Path
import re
import sys
from typing import Any


EXPECTED_REGION_COUNTS = {"East": 66, "North": 49}
EXPECTED_FINDING_COLUMNS = [
    "id",
    "attachment_id",
    "school_ids",
    "matched_alias",
    "person_name",
    "effective_date",
    "reason",
    "matched_line_number",
]
MIN_FINDING_COUNT = 30_000
MAX_ACTIONABLE_REVIEW_COUNT = 1_000
PUBLIC_BASE_PATH = "/boardminutes/"


class ContractViolation(RuntimeError):
    """Raised when a generated public bundle is unsafe to deploy."""


def _require(condition: bool, message: str) -> None:
    if not condition:
        raise ContractViolation(message)


def _load_json(path: Path) -> dict[str, Any]:
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise ContractViolation(f"Cannot read valid JSON from {path}: {exc}") from exc
    _require(isinstance(value, dict), f"{path} must contain a JSON object")
    return value


def _validate_assets(docs_dir: Path) -> int:
    checked = 0
    asset_pattern = re.compile(r'(?:src|href)="(/boardminutes/[^"?#]+)')
    for html_path in docs_dir.rglob("*.html"):
        text = html_path.read_text(encoding="utf-8")
        _require('"/assets/' not in text, f"{html_path} contains a root-relative /assets reference")
        for public_path in asset_pattern.findall(text):
            relative_path = public_path.removeprefix(PUBLIC_BASE_PATH)
            if not (
                relative_path.startswith("assets/")
                or relative_path.startswith("app/")
                or relative_path == "parser-worker.js"
            ):
                continue
            checked += 1
            _require(
                (docs_dir / relative_path).is_file(),
                f"{html_path} references missing deployed file {public_path}",
            )
    _require(checked > 0, "No deployable /boardminutes asset references were found")
    return checked


def _validate_browser_state_persistence(docs_dir: Path) -> str:
    app_assets = list((docs_dir / "assets").glob("BoardWatchApp-*.js"))
    _require(len(app_assets) == 1, "Exactly one BoardWatchApp asset must be deployable")
    app_asset = app_assets[0]
    text = app_asset.read_text(encoding="utf-8")
    unsafe_initial_write = re.compile(
        r"useEffect\)\(\(\)=>\$\([^,]+,([A-Za-z_$][A-Za-z0-9_$]*)\),\[\1\]\)"
    )
    _require(
        unsafe_initial_write.search(text) is None,
        "BoardWatchApp writes browser state before initial data hydration",
    )
    return app_asset.name


def validate_bundle(
    docs_dir: Path,
    *,
    expected_regions: dict[str, int] | None = None,
    min_findings: int = MIN_FINDING_COUNT,
    max_review_queue: int = MAX_ACTIONABLE_REVIEW_COUNT,
) -> dict[str, Any]:
    docs_dir = docs_dir.resolve()
    data_dir = docs_dir / "data"
    board = _load_json(data_dir / "board-data.json")
    findings = _load_json(data_dir / "default-findings.json")
    schools_payload = _load_json(data_dir / "default-schools.json")
    try:
        last_updated = (data_dir / "last-updated.txt").read_text(encoding="utf-8").strip()
    except OSError as exc:
        raise ContractViolation(f"Cannot read last-updated.txt: {exc}") from exc

    generated_at = str(board.get("generated_at") or "")
    _require(generated_at != "", "board-data.json is missing generated_at")
    _require(last_updated == generated_at, "last-updated.txt must equal board-data.json generated_at")
    _require(board.get("errors") == [], "board-data.json contains scanner errors")

    attachments = board.get("attachments")
    _require(isinstance(attachments, list) and attachments, "board-data.json has no attachments")
    attachment_by_id: dict[str, dict[str, Any]] = {}
    for attachment in attachments:
        _require(isinstance(attachment, dict), "Every attachment must be an object")
        attachment_id = str(attachment.get("attachment_id") or "")
        _require(attachment_id != "", "An attachment is missing attachment_id")
        _require(attachment_id not in attachment_by_id, f"Duplicate attachment ID {attachment_id}")
        attachment_by_id[attachment_id] = attachment

    source = board.get("source")
    _require(isinstance(source, dict), "board-data.json is missing source metadata")
    _require(
        source.get("compared_to_previous_export") is True,
        "Routine deployment must be compared to the previous export",
    )
    reported_new_count = source.get("new_attachment_count")
    _require(isinstance(reported_new_count, int), "source.new_attachment_count must be an integer")
    flagged_new_count = sum(
        attachment.get("is_new_since_previous_export") is True for attachment in attachments
    )
    _require(
        flagged_new_count == reported_new_count,
        "source.new_attachment_count does not match attachment flags",
    )

    schools = schools_payload.get("schools")
    board_schools = board.get("schools")
    _require(isinstance(schools, list) and schools, "default-schools.json has no schools")
    _require(isinstance(board_schools, list) and board_schools, "board-data.json has no schools")

    school_by_id: dict[str, dict[str, Any]] = {}
    for school in schools:
        _require(isinstance(school, dict), "Every default school must be an object")
        school_id = str(school.get("school_id") or "")
        _require(school_id != "", "A default school is missing school_id")
        _require(school_id not in school_by_id, f"Duplicate school ID {school_id}")
        school_by_id[school_id] = school

    region_counts = Counter(str(school.get("region") or "") for school in schools)
    required_regions = expected_regions or EXPECTED_REGION_COUNTS
    for region, expected_count in required_regions.items():
        _require(
            region_counts[region] == expected_count,
            f"Region {region} must contain {expected_count} schools; found {region_counts[region]}",
        )

    board_region_by_id = {
        str(school.get("school_id") or ""): str(school.get("region") or "")
        for school in board_schools
        if isinstance(school, dict)
    }
    _require(
        set(board_region_by_id) == set(school_by_id),
        "board-data.json and default-schools.json must contain the same school IDs",
    )
    for school_id, school in school_by_id.items():
        expected_region = str(school.get("region") or "")
        _require(
            board_region_by_id[school_id] == expected_region,
            f"Region mismatch for school {school_id}",
        )

    _require(findings.get("schema_version") == 2, "default-findings.json must use compact schema v2")
    columns = findings.get("columns")
    rows = findings.get("finding_rows")
    _require(columns == EXPECTED_FINDING_COLUMNS, "default-findings.json columns changed unexpectedly")
    _require(isinstance(rows, list), "default-findings.json finding_rows must be an array")
    _require(len(rows) >= min_findings, f"Finding count {len(rows)} is below safety floor {min_findings}")

    column_index = {name: index for index, name in enumerate(columns)}
    finding_ids: set[str] = set()
    actionable_review_count = 0
    review_regions: Counter[str] = Counter()
    for row_number, row in enumerate(rows, start=1):
        _require(
            isinstance(row, list) and len(row) == len(columns),
            f"Finding row {row_number} does not match the compact schema",
        )
        finding_id = str(row[column_index["id"]] or "")
        _require(finding_id != "", f"Finding row {row_number} is missing id")
        _require(finding_id not in finding_ids, f"Duplicate finding ID {finding_id}")
        finding_ids.add(finding_id)

        attachment_id = str(row[column_index["attachment_id"]] or "")
        _require(
            attachment_id in attachment_by_id,
            f"Finding {finding_id} references unknown attachment {attachment_id}",
        )
        attachment = attachment_by_id[attachment_id]
        person_name = str(row[column_index["person_name"]] or "").strip()
        effective_date = str(row[column_index["effective_date"]] or "").strip()
        reason = str(row[column_index["reason"]] or "").strip()
        missing_required_reason = (
            str(attachment.get("movement_type") or "") == "separation"
            and re.search(
                r"licensed\s+personnel\s+separations",
                str(attachment.get("item_title") or ""),
                re.IGNORECASE,
            )
            is not None
            and not reason
        )
        if not person_name or not effective_date or missing_required_reason:
            actionable_review_count += 1
            school_ids = row[column_index["school_ids"]]
            if isinstance(school_ids, list):
                regions = {
                    str(school_by_id.get(str(school_id), {}).get("region") or "")
                    for school_id in school_ids
                }
                for region in regions - {""}:
                    review_regions[region] += 1

    _require(
        actionable_review_count <= max_review_queue,
        "Actionable Review Queue grew to "
        f"{actionable_review_count}; deployment ceiling is {max_review_queue}",
    )

    checked_assets = _validate_assets(docs_dir)
    browser_state_asset = _validate_browser_state_persistence(docs_dir)
    return {
        "generated_at": generated_at,
        "meetings": len(board.get("meetings") or []),
        "attachments": len(attachments),
        "new_attachments": flagged_new_count,
        "findings": len(rows),
        "review_queue": actionable_review_count,
        "review_queue_by_region": dict(sorted(review_regions.items())),
        "regions": dict(sorted(region_counts.items())),
        "asset_references_checked": checked_assets,
        "browser_state_asset": browser_state_asset,
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("docs_dir", nargs="?", default="docs", type=Path)
    args = parser.parse_args(argv)
    try:
        metrics = validate_bundle(args.docs_dir)
    except ContractViolation as exc:
        print(f"PUBLIC BUNDLE CONTRACT FAILED: {exc}", file=sys.stderr)
        return 1
    print(json.dumps(metrics, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
